<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Data-Cleaning" data-toc-modified-id="Data-Cleaning-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Data Cleaning</a></span></li><li><span><a href="#Examining-Data-for-Potential-Issues" data-toc-modified-id="Examining-Data-for-Potential-Issues-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Examining Data for Potential Issues</a></span></li><li><span><a href="#Missing-Values" data-toc-modified-id="Missing-Values-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Missing Values</a></span><ul class="toc-item"><li><span><a href="#Show-the-number-of-null-values-only-of-the-columns-that-actually-have-null-values" data-toc-modified-id="Show-the-number-of-null-values-only-of-the-columns-that-actually-have-null-values-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Show the number of null values only of the columns that actually have null values</a></span></li><li><span><a href="#Remove-the-columns-that-have-more-than-10,000-null-values-in-them" data-toc-modified-id="Remove-the-columns-that-have-more-than-10,000-null-values-in-them-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Remove the columns that have more than 10,000 null values in them</a></span></li><li><span><a href="#Create-a-new-dataframe-that-shows-only-the-row-where-displ-is-null." data-toc-modified-id="Create-a-new-dataframe-that-shows-only-the-row-where-displ-is-null.-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>Create a new dataframe that shows only the row where <code>displ</code> is null.</a></span></li><li><span><a href="#Fill-nan-values-with-the-most-appropriate-technique" data-toc-modified-id="Fill-nan-values-with-the-most-appropriate-technique-3.4"><span class="toc-item-num">3.4&nbsp;&nbsp;</span>Fill nan values with the most appropriate technique</a></span></li><li><span><a href="#Bonus:" data-toc-modified-id="Bonus:-3.5"><span class="toc-item-num">3.5&nbsp;&nbsp;</span>Bonus:</a></span></li></ul></li><li><span><a href="#Incorrect-Values" data-toc-modified-id="Incorrect-Values-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Incorrect Values</a></span><ul class="toc-item"><li><span><a href="#Check-similar-rows" data-toc-modified-id="Check-similar-rows-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Check similar rows</a></span></li><li><span><a href="#Bonus:" data-toc-modified-id="Bonus:-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Bonus:</a></span></li></ul></li><li><span><a href="#Low-Variance-Columns" data-toc-modified-id="Low-Variance-Columns-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Low Variance Columns</a></span><ul class="toc-item"><li><span><a href="#Use-the-the-drop-method-like-we-did-earlier-in-this-lesson-to-remove-the-non-informative-columns-from-our-data-frame." data-toc-modified-id="Use-the-the-drop-method-like-we-did-earlier-in-this-lesson-to-remove-the-non-informative-columns-from-our-data-frame.-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>Use the the drop method like we did earlier in this lesson to remove the non informative columns from our data frame.</a></span></li></ul></li><li><span><a href="#Extreme-Values-and-Outliers" data-toc-modified-id="Extreme-Values-and-Outliers-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Extreme Values and Outliers</a></span></li><li><span><a href="#Data-Type-Correction" data-toc-modified-id="Data-Type-Correction-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Data Type Correction</a></span><ul class="toc-item"><li><span><a href="#Check-the-data-type-of-each-column" data-toc-modified-id="Check-the-data-type-of-each-column-7.1"><span class="toc-item-num">7.1&nbsp;&nbsp;</span>Check the data type of each column</a></span></li><li><span><a href="#Cleaning-years" data-toc-modified-id="Cleaning-years-7.2"><span class="toc-item-num">7.2&nbsp;&nbsp;</span>Cleaning years</a></span></li></ul></li><li><span><a href="#Cleaning-Text-and-Removing-Special-Characters" data-toc-modified-id="Cleaning-Text-and-Removing-Special-Characters-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Cleaning Text and Removing Special Characters</a></span></li><li><span><a href="#Finding-and-Removing-Duplicates" data-toc-modified-id="Finding-and-Removing-Duplicates-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>Finding and Removing Duplicates</a></span><ul class="toc-item"><li><span><a href="#Drop-duplicate-rows-that-are-completely-equal" data-toc-modified-id="Drop-duplicate-rows-that-are-completely-equal-9.1"><span class="toc-item-num">9.1&nbsp;&nbsp;</span>Drop duplicate rows that are completely equal</a></span></li><li><span><a href="#Select-a-subset-of-columns,-remove-all-other-columns,-and-then-use-the-drop_duplicates-method-to-drop-any-duplicate-records-based-on-the-remaining-columns." data-toc-modified-id="Select-a-subset-of-columns,-remove-all-other-columns,-and-then-use-the-drop_duplicates-method-to-drop-any-duplicate-records-based-on-the-remaining-columns.-9.2"><span class="toc-item-num">9.2&nbsp;&nbsp;</span>Select a subset of columns, remove all other columns, and then use the drop_duplicates method to drop any duplicate records based on the remaining columns.</a></span></li></ul></li><li><span><a href="#Export-clean-dataset" data-toc-modified-id="Export-clean-dataset-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>Export clean dataset</a></span></li></ul></div>

# Data Cleaning


Lab Goals

+ Examine data for potential issues.
+ Identify and fill in missing values.
+ Identify and correct incorrect values.
+ Remove low variance columns.
+ Identify potential outliers.
+ Correct incorrect data types.
+ Remove special characters and clean categorical variables.
+ Identify and remove duplicate records.

Introduction

When working with data sets, you will find that they often require a bit of cleaning. Whether Pandas originally read the data types incorrectly, records are duplicated, the data contains special characters or missing value, or there are slightly different references to the same entity, every data analyst must know how to clean the data they are working with before analyzing it. In this lesson, you will learn about some of the most common problems that make data messy and methods for correcting those problems and cleaning your data.

The data set we are going to be using for this lesson is a messy version of the vehicles data set we worked with in the previous lesson. Let's import this version of our data set so that we can then practice cleaning it up.

In [1]:
import pandas as pd
import numpy as np
import warnings
import pylab as plt   # import matplotlib.pyplot as plt
import seaborn as sns
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None)
%matplotlib inline

In [2]:
URL= r'C:\Users\carol\Ironhack\2.4-lab_data_cleaning\data\vehicles_messy.csv'

In [3]:
#Load data from vehicles_messy.csv
import csv
data_original = pd.read_csv(URL)

In [4]:
data= data_original.copy()

# Examining Data for Potential Issues

One of the first things we want to do is examine the data and look for any **potential issues**. Some of the things we are interested in identifying in the data at this stage include:

- Missing values
- Special characters
- Incorrect values
- Extreme values or outliers
- Duplicate records
- Incorrect data types

The presence of these may cause problems when it's time to analyze the data, so we want to make sure we address them beforehand. We can start by visually inspecting the data using the `.head` method, which will show us the first 5 rows of data.

In [5]:
data.head()

,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,drive,engId,eng_dscr,feScore,fuelCost08,fuelCostA08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,make,model,mpgData,phevBlended,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,trany,UCity,UCityA,UHighway,UHighwayA,VClass,year,youSaveSpend,guzzler,trans_dscr,tCharger,sCharger,atvType,fuelType2,rangeA,evMotor,mfrCode,c240Dscr,charge240b,c240bDscr,createdOn,modifiedOn,startStop,phevCity,phevHwy,phevComb
0,15.695714,0.0,0.0,0.0,19,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,423.190476,21,0.0,0,0.0,0.0,0.0,0.0,4.0,2.0,Rear-Wheel Drive,9011,(FFS),-1,1600,0,Regular,Regular Gasoline,-1,-1,25,0.0,0,0.0,0.0,0.0,0.0,0,0,1,0,0,Alfa Romeo,Spider Veloce 2000,Y,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,23.3333,0.0,35.0000,0.0,Two Seaters,1985,-1250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
1,29.964545,0.0,0.0,0.0,9,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,12.0,4.9,Rear-Wheel Drive,22020,(GUZZLER),-1,3050,0,Regular,Regular Gasoline,-1,-1,14,0.0,0,0.0,0.0,0.0,0.0,0,0,10,0,0,Ferrari,Testarossa,N,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,11.0000,0.0,19.0000,0.0,Two Seaters,1985,-8500,T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
2,12.207778,0.0,0.0,0.0,23,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,329.148148,27,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,Front-Wheel Drive,2100,(FFS),-1,1250,0,Regular,Regular Gasoline,-1,-1,33,0.0,0,0.0,0.0,0.0,0.0,19,77,100,0,0,Dodge,Charger,Y,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,29.0000,0.0,47.0000,0.0,Subcompact Cars,1985,500,NaN,SIL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
3,29.964545,0.0,0.0,0.0,10,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,8.0,5.2,Rear-Wheel Drive,2850,NaN,-1,3050,0,Regular,Regular Gasoline,-1,-1,12,0.0,0,0.0,0.0,0.0,0.0,0,0,1000,0,0,Dodge,B150/B250 Wagon 2WD,N,False,0,0,0,0.0,0.0,0.0,0.0,Automatic 3-spd,12.2222,0.0,16.6667,0.0,Vans,1985,-8500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
4,17.347895,0.0,0.0,0.0,17,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,467.736842,19,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66031,"(FFS,TRBO)",-1,2150,0,Premium,Premium Gasoline,-1,-1,23,0.0,0,0.0,0.0,0.0,0.0,0,0,10000,0,14,Subaru,Legacy AWD Turbo,N,False,0,90,0,0.0,0.0,0.0,0.0,Manual 5-spd,21.0000,0.0,32.0000,0.0,Compact Cars,1993,-4000,NaN,NaN,T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0

But how big actually is our dataframe??? Check it with `.shape` method

In [6]:
data.shape

(37843, 83)

Let's dive a little more in the content of our data set. Is there any method that shows us the **column names**, its **data types** and number of **non-null values**?

In [7]:
data.columns

Index(['barrels08', 'barrelsA08', 'charge120', 'charge240', 'city08',
       'city08U', 'cityA08', 'cityA08U', 'cityCD', 'cityE', 'cityUF', 'co2',
       'co2A', 'co2TailpipeAGpm', 'co2TailpipeGpm', 'comb08', 'comb08U',
       'combA08', 'combA08U', 'combE', 'combinedCD', 'combinedUF', 'cylinders',
       'displ', 'drive', 'engId', 'eng_dscr', 'feScore', 'fuelCost08',
       'fuelCostA08', 'fuelType', 'fuelType1', 'ghgScore', 'ghgScoreA',
       'highway08', 'highway08U', 'highwayA08', 'highwayA08U', 'highwayCD',
       'highwayE', 'highwayUF', 'hlv', 'hpv', 'id', 'lv2', 'lv4', 'make',
       'model', 'mpgData', 'phevBlended', 'pv2', 'pv4', 'range', 'rangeCity',
       'rangeCityA', 'rangeHwy', 'rangeHwyA', 'trany', 'UCity', 'UCityA',
       'UHighway', 'UHighwayA', 'VClass', 'year', 'youSaveSpend', 'guzzler',
       'trans_dscr', 'tCharger', 'sCharger', 'atvType', 'fuelType2', 'rangeA',
       'evMotor', 'mfrCode', 'c240Dscr', 'charge240b', 'c240bDscr',
       'createdOn', 'modifiedOn', 'startStop', 'phevCity', 'phevHwy',
       'phevComb'],
      dtype='object')

In [8]:
data.dtypes

barrels08     float64
barrelsA08    float64
charge120     float64
charge240     float64
city08          int64
               ...
modifiedOn     object
startStop      object
phevCity        int64
phevHwy         int64
phevComb        int64
Length: 83, dtype: object

In [9]:
#Objetivo-> Identificar los automóviles más eficientes en cuanto combustible.
#¿Qué columnas me interesa para conseguir mi objetivo? -> 'city08' (millas por galón en ciudad) ; 'highway08' (millas por galón en carretera);'comb08'(eficiencia de combustible combinada);'fuelType' ; 'fuelType1';'cylinders'; 'displ';'VClass'; 'year'; 'make' ; 'model'
#1ºLimpio datos
#2ºSelección columnas relevantes
#3ºCalcular una métrica de eficiencia(puede ser el promedio ponderado de la eficiencia en ciudad y carretera)
#4ºOrdenar por eficiencia
#5ºVisualización por resultado
#6ºFiltrar por año o tipo de vehículo
#7ºPresentación de resultados

## Missing Values

From this initial view, we can see that our data set contains some columns that have missing values in them and others that seem to have a lot of zero values.

Let's see how prevalent missing values are in our data. We can use the Pandas .isnull() method to check whether the value in each field is missing (null) and return either True or False for each field.

We can use the .sum() method to total up the number of True values by column, and then we can add a condition using square brackets that will filter the data and show us only columns where the number of null values were greater than zero.

In [10]:
data.isnull()

,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,drive,engId,eng_dscr,feScore,fuelCost08,fuelCostA08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,make,model,mpgData,phevBlended,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,trany,UCity,UCityA,UHighway,UHighwayA,VClass,year,youSaveSpend,guzzler,trans_dscr,tCharger,sCharger,atvType,fuelType2,rangeA,evMotor,mfrCode,c240Dscr,charge240b,c240bDscr,createdOn,modifiedOn,startStop,phevCity,phevHwy,phevComb
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True,True,False,True,False,False,True,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True,False,True,False,False,True,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,True,True,True,True,True,True,False,True,False,False,True,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True,True,False,True,False,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,True,True,True,True,True,True,True,False,True,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37838,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,True,True,True,True,True,True,False,True,False,False,True,False,False,False
37839,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True,True,False,True,False,False,True,False,False,False
37840,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,True,True,True,True,True,True,False,True,False,False,True,False,False,False
37841,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True,True,False,True,False,False,True,False,False,False
37842,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,True,True,True,True,True,True,False,True,False,False,True,False,False,False

In [11]:
non_nulls=data.isnull().sum()
non_nulls

barrels08         0
barrelsA08        0
charge120         0
charge240         0
city08            0
              ...
modifiedOn        0
startStop     31705
phevCity          0
phevHwy           0
phevComb          0
Length: 83, dtype: int64

## Show the number of null values only of the columns that actually have null values

We can see that some columns have relatively few null values while others have tens of thousands of nulls. For fields that have a lot of null values, you will often have to make a judgement call. If you don't think the information is going to be very useful to your analysis, then you would remove those columns from your data frame.

In [12]:
non_nulls[non_nulls>0]

cylinders       123
displ           120
drive          1189
eng_dscr      15403
trany            11
guzzler       35562
trans_dscr    22796
tCharger      32657
sCharger      37177
atvType       34771
fuelType2     36435
rangeA        36440
evMotor       37281
mfrCode       30818
c240Dscr      37806
c240bDscr     37807
startStop     31705
dtype: int64

## Remove the columns that have more than 10,000 null values in them

In Pandas, we can do that using the drop method. For our purposes, let's remove the columns that have more than 10,000 null values in them. We will add these column names to a list, and then we will pass those columns to the drop method and indicate that we want columns (not rows) dropped by setting the axis parameter to 1.

In [13]:
non_nulls[non_nulls>10000].index #esto me proporciona los índices de las columnas de la condición que he escrito

Index(['eng_dscr', 'guzzler', 'trans_dscr', 'tCharger', 'sCharger', 'atvType',
       'fuelType2', 'rangeA', 'evMotor', 'mfrCode', 'c240Dscr', 'c240bDscr',
       'startStop'],
      dtype='object')

In [14]:
data.drop(columns= non_nulls[non_nulls>10000].index, axis=1, inplace=True)

In [15]:
data_original.shape , data.shape #compruebo si han bajado las columnas>10000

((37843, 83), (37843, 70))

This leaves us with just a handful of remaining columns that have null values. Of the columns that remain, it looks like the cylinders column and the displ column have a similar number of nulls. Perhaps they are missing for similar reasons. We can investigate this by subsetting the data set and looking at just the records where displ is null and just the columns we think will be informative in allowing us to determine a reason.

In [16]:
#vovler a identificar si hay valores nulos
non_nulls2 = data.isnull().sum()
non_nulls2

barrels08     0
barrelsA08    0
charge120     0
charge240     0
city08        0
             ..
createdOn     0
modifiedOn    0
phevCity      0
phevHwy       0
phevComb      0
Length: 70, dtype: int64

In [17]:
non_nulls2[non_nulls2>0] #sigo con estos nulos,¿qué hago?

cylinders     123
displ         120
drive        1189
trany          11
dtype: int64

In [18]:
data[['cylinders','displ']].describe()

          cylinders         displ
count  37720.000000  37723.000000
mean       5.737990      3.318180
std        1.751795      1.361399
min        2.000000      0.000000
25%        4.000000      2.200000
50%        6.000000      3.000000
75%        6.000000      4.300000
max       16.000000      8.400000

In [19]:
#calculo la correlación
correlacion=data['cylinders'].corr(data['displ'])

'''
Esto indica una correlación positiva y muy fuerte este las dos variables. 
Esta cerca a 1, lo que sugiere que hay una relación lineal positiva, por lo
que, es probable que los valores nulos en estas dos columnas estén relacionados.
'''
correlacion

0.902694518984286

## Create a new dataframe that shows only the row where `displ` is null. 
Keep only the columns you think are useful

In [20]:
null_valores_subset= data[data['cylinders'].isnull() & data['displ'].isnull()]
null_valores_subset.head().T

,7138,7139,8143,8144,8146
barrels08,0.24,0.282,0.282,0.312,0.522
barrelsA08,0.0,0.0,0.0,0.0,0.0
charge120,0.0,0.0,0.0,0.0,0.0
charge240,0.0,0.0,0.0,0.0,0.0
city08,81,81,81,74,45
...,...,...,...,...,...
createdOn,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013
modifiedOn,Thu Jul 07 00:00:00 EDT 2016,Thu Jul 07 00:00:00 EDT 2016,Thu Jul 07 00:00:00 EDT 2016,Thu Jul 07 00:00:00 EDT 2016,Thu Jul 07 00:00:00 EDT 2016
phevCity,0,0,0,0,0
phevHwy,0,0,0,0,0
phevComb,0,0,0,0,0

In [21]:
data['cylinders'] = data['cylinders'].notna().astype(int)
data['displ'] = data['displ'].notna().astype(int)

#primero aplico el método .notna() pra verificar si los valores no son nulos
#luego .astype(int) para convertir los valores T/F en 1 y 0, respectivamente en las columnas seleccionadas.

In [22]:
data

,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,drive,engId,feScore,fuelCost08,fuelCostA08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,make,model,mpgData,phevBlended,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,trany,UCity,UCityA,UHighway,UHighwayA,VClass,year,youSaveSpend,charge240b,createdOn,modifiedOn,phevCity,phevHwy,phevComb
0,15.695714,0.0,0.0,0.0,19,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,423.190476,21,0.0,0,0.0,0.0,0.0,0.0,1,1,Rear-Wheel Drive,9011,-1,1600,0,Regular,Regular Gasoline,-1,-1,25,0.0,0,0.0,0.0,0.0,0.0,0,0,1,0,0,Alfa Romeo,Spider Veloce 2000,Y,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,23.3333,0.0,35.0000,0.0,Two Seaters,1985,-1250,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
1,29.964545,0.0,0.0,0.0,9,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,1,1,Rear-Wheel Drive,22020,-1,3050,0,Regular,Regular Gasoline,-1,-1,14,0.0,0,0.0,0.0,0.0,0.0,0,0,10,0,0,Ferrari,Testarossa,N,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,11.0000,0.0,19.0000,0.0,Two Seaters,1985,-8500,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
2,12.207778,0.0,0.0,0.0,23,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,329.148148,27,0.0,0,0.0,0.0,0.0,0.0,1,1,Front-Wheel Drive,2100,-1,1250,0,Regular,Regular Gasoline,-1,-1,33,0.0,0,0.0,0.0,0.0,0.0,19,77,100,0,0,Dodge,Charger,Y,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,29.0000,0.0,47.0000,0.0,Subcompact Cars,1985,500,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
3,29.964545,0.0,0.0,0.0,10,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,1,1,Rear-Wheel Drive,2850,-1,3050,0,Regular,Regular Gasoline,-1,-1,12,0.0,0,0.0,0.0,0.0,0.0,0,0,1000,0,0,Dodge,B150/B250 Wagon 2WD,N,False,0,0,0,0.0,0.0,0.0,0.0,Automatic 3-spd,12.2222,0.0,16.6667,0.0,Vans,1985,-8500,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
4,17.347895,0.0,0.0,0.0,17,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,467.736842,19,0.0,0,0.0,0.0,0.0,0.0,1,1,4-Wheel or All-Wheel Drive,66031,-1,2150,0,Premium,Premium Gasoline,-1,-1,23,0.0,0,0.0,0.0,0.0,0.0,0,0,10000,0,14,Subaru,Legacy AWD Turbo,N,False,0,90,0,0.0,0.0,0.0,0.0,Manual 5-spd,21.0000,0.0,32.0000,0.0,Compact Cars,1993,-4000,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37838,14.982273,0.0,0.0,0.0,19,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,403.954545,22,0.0,0,0.0,0.0,0.0,0.0,1,1,Front-Wheel Drive,66030,-1,1500,0,Regular,Regular Gasoline,-1,-1,26,0.0,0,0.0,0.0,0.0,0.0,0,0,9995,0,14,Subaru,Legacy,N,False,0,90,0,0.0,0.0,0.0,0.0,Automatic 4-spd,24.0000,0.0,37.0000,0.0,Compact Cars,1993,-750,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
37839,14.330870,0.0,0.0,0.0,20,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,386.391304,23,0.0,0,0.0,0.0,0.0,0.0,1,1,Front-Wheel Drive,66030,-1,1450,0,Regular,Regular Gasoline,-1,-1,28,0.0,0,0.0,0.0,0.0,0.0,0,0,9996,0,14,Subaru,Legacy,N,False,0,90,0,0.0,0.0,0.0,0.0,Manual 5-spd,25.0000,0.0,39.0000,0.0,Compact Cars,1993,-500,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
37840,15.695714,0.0,0.0,0.0,18,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,423.190476,21,0.0,0,0.0,0.0,0.0,0.0,1,1,4-Wheel or All-Wheel Drive,66030,-1,1600,0,Regular,Regular Gasoline,-1,-1,24,0.0,0,0.0,0.0,0.0,0.0,0,0,9997,0,14,Subaru,Legacy AWD,Y,False,0,90,0,0.0,0.0,0.0,0.0,Automatic 4-spd,23.0000,0.0,34.0000,0.0,Compact Cars,1993,-1250,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
37841,15.695714,0.0,0.0,0.0,18,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,423.190476,21,0.0,0,0.0,0.0,0.0,0.0,1,1,4-Wheel or All-Wheel Drive,66030,-1,1600,0,Regular,Regular Gasoline,-1,-1,24,0.0,0,0.0,0.0,0.0,0.0,0,0,9998,0,14,Subaru,Legacy AWD,N,False,0,90,0,0.0,0.0,0.0,0.0,Manual 5-spd,23.0000,0.0,34.0000,0.0,Compact Cars,1993,-1250,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
37842,18.311667,0.0,0.0,0.0,16,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,493.722222,18,0.0,0,0.0,0.0,0.0,0.0,1,1,4-Wheel or All-Wheel Drive,66031,-1,2250,0,Premium,Premium Gasoline,-1,-1,21,0.0,0,0.0,0.0,0.0,0.0,0,0,9999,0,14,Subaru,Legacy AWD Turbo,N,False,0,90,0,0.0,0.0,0.0,0.0,Automatic 4-spd,20.0000,0.0,29.0000,0.0,Compact Cars,1993,-4500,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0

## Fill nan values with the most appropriate technique 
*HINT: Electric cars do not have cylinders and can therefore not have any displacement*

In [23]:
#¡¡Hecho en el apartado 3.3!!

## Bonus: 
Now that we have filled in those null values, there are only two columns in the data set that still have null values: trany and drive. Use what you have learned in this section to investigate and potentially fill in the remaining null values.

In [24]:
print(data['trany'].isnull().sum())
print(data['drive'].isnull().sum())

11
1189

In [25]:
data.shape,data_original.shape

((37843, 70), (37843, 83))

In [26]:
print(data['trany'].value_counts())
print(data['drive'].value_counts())

trany
Automatic 4-spd                     11042
Manual 5-spd                         8311
Automatic 3-spd                      3151
Automatic (S6)                       2638
Manual 6-spd                         2429
Automatic 5-spd                      2184
Manual 4-spd                         1483
Automatic 6-spd                      1432
Automatic (S8)                        960
Automatic (S5)                        824
Automatic (variable gear ratios)      681
Automatic 7-spd                       663
Automatic (S7)                        261
Auto(AM-S7)                           256
Automatic 8-spd                       243
Automatic (S4)                        233
Auto(AM7)                             160
Auto(AV-S6)                           145
Auto(AM6)                             110
Automatic (A1)                        109
Auto(AM-S6)                            92
Automatic 9-spd                        90
Manual 3-spd                           77
Manual 7-spd                           68
Auto(AV-S7)                            63
Auto(AV-S8)                            26
Automatic (S9)                         26
Manual 4-spd Doubled                   17
Auto(AM5)                              12
Automatic (AV-S6)                       9
Auto(AM-S8)                             6
Auto(AM8)                               5
Automatic (AV)                          4
Automatic (A6)                          4
Manual(M7)                              3
Auto(L4)                                2
Auto(L3)                                2
Automatic (AM5)                         2
Auto (AV)                               2
Auto(A1)                                1
Automatic (AM6)                         1
Automatic 6spd                          1
Auto (AV-S8)                            1
Auto (AV-S6)                            1
Manual 5 spd                            1
Auto(AM-S9)                             1
Name: count, dtype: int64
drive
Front-Wheel Drive             13286
Rear-Wheel Drive              12931
4-Wheel or All-Wheel Drive     6648
All-Wheel Drive                2057
4-Wheel Drive                  1065
2-Wheel Drive                   507
Part-time 4-Wheel Drive         159
2-Wheel Drive, Front              1
Name: count, dtype: int64

In [27]:
def analyze_column_values(data, column_name):
    print(f"Valores en la columna '{column_name}':")
    print(data[column_name].value_counts())


analyze_column_values(data, 'trany')

analyze_column_values(data, 'drive')

Valores en la columna 'trany':
trany
Automatic 4-spd                     11042
Manual 5-spd                         8311
Automatic 3-spd                      3151
Automatic (S6)                       2638
Manual 6-spd                         2429
Automatic 5-spd                      2184
Manual 4-spd                         1483
Automatic 6-spd                      1432
Automatic (S8)                        960
Automatic (S5)                        824
Automatic (variable gear ratios)      681
Automatic 7-spd                       663
Automatic (S7)                        261
Auto(AM-S7)                           256
Automatic 8-spd                       243
Automatic (S4)                        233
Auto(AM7)                             160
Auto(AV-S6)                           145
Auto(AM6)                             110
Automatic (A1)                        109
Auto(AM-S6)                            92
Automatic 9-spd                        90
Manual 3-spd                           77
Manual 7-spd                           68
Auto(AV-S7)                            63
Auto(AV-S8)                            26
Automatic (S9)                         26
Manual 4-spd Doubled                   17
Auto(AM5)                              12
Automatic (AV-S6)                       9
Auto(AM-S8)                             6
Auto(AM8)                               5
Automatic (AV)                          4
Automatic (A6)                          4
Manual(M7)                              3
Auto(L4)                                2
Auto(L3)                                2
Automatic (AM5)                         2
Auto (AV)                               2
Auto(A1)                                1
Automatic (AM6)                         1
Automatic 6spd                          1
Auto (AV-S8)                            1
Auto (AV-S6)                            1
Manual 5 spd                            1
Auto(AM-S9)                             1
Name: count, dtype: int64
Valores en la columna 'drive':
drive
Front-Wheel Drive             13286
Rear-Wheel Drive              12931
4-Wheel or All-Wheel Drive     6648
All-Wheel Drive                2057
4-Wheel Drive                  1065
2-Wheel Drive                   507
Part-time 4-Wheel Drive         159
2-Wheel Drive, Front              1
Name: count, dtype: int64

La mayoría de los valores de 'trany' están en formatos específicos, como "Automatic X-spd" o "Manual Y-spd", donde X e Y son números.Opto por llenar los valores nulos en 'trany' basándome en la moda (valor más común) de los datos existentes de 'trany'. Esto significa que llenaráé los valores nulos con el tipo de transmisión más común.

In [28]:
# Llenar los valores nulos en 'trany' con la moda
mode_trany = data['trany'].mode()[0]
data['trany'].fillna(mode_trany, inplace=True)

In [29]:
data['trany'].isnull().sum()

0

Observo que en la columna 'drive', los valores son categorías más descriptivas como "Front-Wheel Drive" o "Rear-Wheel Drive". Lleno los valores nulos en 'drive' basándome en la moda de los datos existentes de 'drive', de manera similar a 'trany'.

In [30]:
# Llenar los valores nulos en 'drive' con la moda
mode_drive = data['drive'].mode()[0]
data['drive'].fillna(mode_drive, inplace=True)

In [31]:
print(data['trany'].isnull().sum())
print(data['drive'].isnull().sum())

0
0

El llenado de las columnas "trany" y "drive" con la moda se justifica de la siguiente manera:

Para 'trany':

1º Mayor frecuencia de aparición: La moda representa el tipo de transmisión más común entre los vehículos en el conjunto de datos. Esto significa que la mayoría de los vehículos en mi conjunto de datos tienen esta transmisión.

2ºPreservación de la estructura de los datos: Usar la moda para llenar los valores nulos en "trany" garantiza que la mayoría de los vehículos, que tienen esa transmisión común, se mantengan sin cambios. Esto preserva la estructura general de los datos y es una aproximación razonable para llenar los valores nulos.

Para 'drive' (tracción):

1º Identificación de la tracción más común: Llenar con la moda en "drive" significa asignar la tracción que es más común entre los vehículos. Esto ayuda a mantener la consistencia en el conjunto de datos, ya que la mayoría de los vehículos tienen esta tracción común.

2º Facilita el análisis: Al llenar con la moda, se simplifica el análisis y la comparación de vehículos, ya que la mayoría se clasifican en la misma categoría de tracción, lo que facilita la comprensión de los datos y las comparaciones entre vehículos.

En resumen, llenar con la moda en "trany" y "drive" se basa en la idea de que los valores más comunes representan la norma en el conjunto de datos y, por lo tanto, proporcionan una buena aproximación para llenar los valores nulos en ausencia de información más específica. Esta estrategia la he llevado a cabo para preservar la estructura general de los datos y facilitar el análisis.

# Incorrect Values

In addition to null values, we also want to try to identify any values that seem incorrect. For example, in the previous section, we learned that a vehicle without cylinders should not have displacement and vice versa. Let's check to see if there are any cases that violate these rules.

In [32]:
# Identificar valores incorrectos
incorrect_cyl_displ = data[(data['cylinders'] == 0) & (data['displ'] > 0)]
incorrect_displ_cyl = data[(data['cylinders'] > 0) & (data['displ'] == 0)]

In [33]:
# Mostrar los casos con valores incorrectos
print("Casos en los que un vehículo sin cilindros tiene desplazamiento:")
print(incorrect_cyl_displ)

Casos en los que un vehículo sin cilindros tiene desplazamiento:
       barrels08  barrelsA08  charge120  charge240  city08   city08U  cityA08  \
21506  18.311667         0.0        0.0        0.0      15    0.0000        0
28607   0.180000         0.0        0.0        7.0     126  126.3678        0
29060   0.324000         0.0        0.0        6.0      61   61.3200        0

       cityA08U  cityCD  cityE  cityUF  co2  co2A  co2TailpipeAGpm  \
21506       0.0     0.0    0.0     0.0   -1    -1              0.0
28607       0.0     0.0   27.0     0.0    0    -1              0.0
29060       0.0     0.0   55.0     0.0    0    -1              0.0

       co2TailpipeGpm  comb08   comb08U  combA08  combA08U  combE  combinedCD  \
21506      493.722222      18    0.0000        0       0.0    0.0         0.0
28607        0.000000     112  112.2077        0       0.0   30.0         0.0
29060        0.000000      63   62.9357        0       0.0   54.0         0.0

       combinedUF  cylinders  displ              drive  engId  feScore  \
21506         0.0          0      1   Rear-Wheel Drive      0       -1
28607         0.0          0      1   Rear-Wheel Drive    141       10
29060         0.0          0      1  Front-Wheel Drive      1       10

       fuelCost08  fuelCostA08     fuelType         fuelType1  ghgScore  \
21506        1850            0      Regular  Regular Gasoline        -1
28607         600            0  Electricity       Electricity        10
29060        1050            0  Electricity       Electricity        10

       ghgScoreA  highway08  highway08U  highwayA08  highwayA08U  highwayCD  \
21506         -1         22      0.0000           0          0.0        0.0
28607         -1         99     98.6914           0          0.0        0.0
29060         -1         65     65.0300           0          0.0        0.0

       highwayE  highwayUF  hlv  hpv     id  lv2  lv4        make   model  \
21506       0.0        0.0    0    0  29557    0    0       Mazda    RX-7
28607      34.0        0.0   13   85  36023    0    0  Mitsubishi  i-MiEV
29060      52.0        0.0    0    0  36437    0    0         BYD      e6

      mpgData  phevBlended  pv2  pv4  range  rangeCity  rangeCityA  rangeHwy  \
21506       N        False    0    0      0     0.0000         0.0    0.0000
28607       N        False    0    0     62    68.5545         0.0   54.8184
29060       N        False    0    0    127   121.1000         0.0  133.9000

       rangeHwyA           trany     UCity  UCityA  UHighway  UHighwayA  \
21506        0.0    Manual 5-spd   19.0473     0.0   31.1094        0.0
28607        0.0  Automatic (A1)  180.5254     0.0  140.9876        0.0
29060        0.0  Automatic (A1)   87.6000     0.0   92.9000        0.0

                                VClass  year  youSaveSpend  charge240b  \
21506                      Two Seaters  1986         -2500         0.0
28607                  Subcompact Cars  2016          3750         0.0
29060  Small Sport Utility Vehicle 2WD  2015          1500         0.0

                          createdOn                    modifiedOn  phevCity  \
21506  Tue Jan 01 00:00:00 EST 2013  Tue Jan 01 00:00:00 EST 2013         0
28607  Fri Feb 06 00:00:00 EST 2015  Wed Apr 20 00:00:00 EDT 2016         0
29060  Wed Jun 24 00:00:00 EDT 2015  Wed Jun 24 00:00:00 EDT 2015         0

       phevHwy  phevComb
21506        0         0
28607        0         0
29060        0         0

In [34]:
print("\nCasos en los que un vehículo con cilindros tiene desplazamiento igual a cero:")
print(incorrect_displ_cyl)

Casos en los que un vehículo con cilindros tiene desplazamiento igual a cero:
Empty DataFrame
Columns: [barrels08, barrelsA08, charge120, charge240, city08, city08U, cityA08, cityA08U, cityCD, cityE, cityUF, co2, co2A, co2TailpipeAGpm, co2TailpipeGpm, comb08, comb08U, combA08, combA08U, combE, combinedCD, combinedUF, cylinders, displ, drive, engId, feScore, fuelCost08, fuelCostA08, fuelType, fuelType1, ghgScore, ghgScoreA, highway08, highway08U, highwayA08, highwayA08U, highwayCD, highwayE, highwayUF, hlv, hpv, id, lv2, lv4, make, model, mpgData, phevBlended, pv2, pv4, range, rangeCity, rangeCityA, rangeHwy, rangeHwyA, trany, UCity, UCityA, UHighway, UHighwayA, VClass, year, youSaveSpend, charge240b, createdOn, modifiedOn, phevCity, phevHwy, phevComb]
Index: []

Is there any row that seems to have strange values?

In [35]:
# Verificar si hay alguna fila con valores extraños
if (incorrect_cyl_displ.any().any() or incorrect_displ_cyl.any().any()):
    print("Se han encontrado filas con valores extraños.")
else:
    print("No hay filas con valores extraños.")

Se han encontrado filas con valores extraños.

Here we have identified a vehicle with a regular gasoline engine that reportedly does not have any cylinders but does have a value for displacement.

The way we would correct this would be to either perform some domain research or ask a domain expert to find out how many actual cylinders this vehicle had. Alternatively, you can also try to look at similar vehicles in the data set and determine the most likely value for this field.

## Check similar rows

In [36]:
# Índice del vehículo con valores incorrectos
vehicle_index = 21506

# Tipo de combustible y desplazamiento del vehículo en cuestión
fuel_type = data.at[vehicle_index, 'fuelType']
displacement = data.at[vehicle_index, 'displ']

# Filtrar vehículos similares
similar_vehicles = data[(data['fuelType'] == fuel_type) & (data['displ'] == displacement)]

if not similar_vehicles.empty:
    # Calcular la moda de cilindros para vehículos similares
    mode_cylinders = similar_vehicles['cylinders'].mode().iloc[0]

    # Actualizar el valor de cilindros para el vehículo en cuestión
    data.at[vehicle_index, 'cylinders'] = mode_cylinders
    print(f"Se ha actualizado el número de cilindros del vehículo en el índice {vehicle_index} a {mode_cylinders}.")
else:
    print("No se encontraron vehículos similares para estimar el número de cilindros.")

Se ha actualizado el número de cilindros del vehículo en el índice 21506 a 1.

Esto corrige la discrepancia entre el número de cilindros y el desplazamiento para ese vehículo en particular.

Suppose that using one of the aforementioned methods, we found out that this vehicle actually has a 4 cylinder engine. Update that specific value in the data frame.

In [37]:
data.at['21506', 'cylinders']=4

## Bonus: 
 Try to find other values that might be incorrect in the data set based on what you know about automobiles and correct them.

In [38]:
#your code

# Low Variance Columns

When analyzing data, we want the fields we are working with to be informative, and we will want to strip away any columns that don't have a lot of value to us. One easy way to do this is to identify columns that have low variance, where the majority of the values in the column are the same. Since there is not a lot of variability in these columns, they have the potential to not be as informative as columns that have a variety of different values in them.

Let's try to identify columns where at least 90% of the values are the same so that we can remove them from our data set. To do this, we are going to create an empty list called low_variance that will eventually contain the names of columns that fit our criteria.

We will then write a for loop that will take the minimum and the 90th percentile value for all the numeric columns in our data set (identified via the _get_numeric_data method). If the 90th percentile and the minimum are equal to each other, that means that at least 90% of the values in that column are the same and we will append that column name to our low_variance list.

In [39]:
#your code
low_variance = []
numeric_columns = data._get_numeric_data()
for column in numeric_columns:
    percentile_90 = numeric_columns[column].quantile(0.90)
    min_value = numeric_columns[column].min()
    if percentile_90 == min_value:
        low_variance.append(column)

print("Columnas con baja variabilidad (al menos el 90% de valores iguales):")
print(low_variance)

Columnas con baja variabilidad (al menos el 90% de valores iguales):
['barrelsA08', 'charge120', 'charge240', 'cityA08', 'cityA08U', 'cityCD', 'cityE', 'cityUF', 'co2A', 'co2TailpipeAGpm', 'combA08', 'combA08U', 'combE', 'combinedCD', 'combinedUF', 'fuelCostA08', 'ghgScoreA', 'highwayA08', 'highwayA08U', 'highwayCD', 'highwayE', 'highwayUF', 'range', 'rangeCity', 'rangeCityA', 'rangeHwy', 'rangeHwyA', 'UCityA', 'UHighwayA', 'charge240b', 'phevCity', 'phevHwy', 'phevComb']

In [40]:
count_low_variance = len(low_variance)
print("Número de columnas con baja variabilidad:", count_low_variance)

Número de columnas con baja variabilidad: 33

This returned 34 columns that we could potentially eliminate due to not having high enough variability to be informative. Of course, before we do this, we should check the values that do exist in these fields to confirm that they are not very informative. Once they have been checked, we can use the the drop method like we did earlier in this lesson to remove those columns from our data frame.

## Use the the drop method like we did earlier in this lesson to remove the non informative columns from our data frame.

In [41]:
data.drop(columns=low_variance, inplace=True)

In [42]:
data_original.shape,data.shape

((37843, 83), (37844, 37))

# Extreme Values and Outliers

Now that we have removed low variance columns, we should look for outliers, or extreme values, in the columns that remain. These outliers can influence our aggregations when we are analyzing data later, so we want to make sure we address them during our data cleaning stage.

A common method for identifying outliers is one that leverages the interquartile range (IQR). Once the IQR is calculated, it is multiplied by a constant (typically 1.5) and lower and upper bounds are established at:

    25th Percentile - (IQR x 1.5)
    75th Percentile + (IQR x 1.5)

Any values outside this range are potential outliers and should be investigated.

Let's look at how we would do this for our data set using Python. We will use the Pandas describe function to easily calculate the 25th and 75th percentiles for every column and transpose the results so that we can easily reference the values in calculating the interquartile ranges.

In [43]:
#Run this code
stats = data.describe().transpose()
stats['IQR'] = stats['75%'] - stats['25%']
stats

,count,mean,std,min,25%,50%,75%,max,IQR
barrels08,37843.0,17.532506,4.575950,0.06,14.33087,17.347895,20.600625,47.087143,6.269755
city08,37843.0,17.941389,6.660360,6.00,15.00000,17.000000,20.000000,138.000000,5.000000
city08U,37843.0,4.042737,9.645820,0.00,0.00000,0.000000,0.000000,138.304000,0.000000
co2,37843.0,61.503713,153.387715,-1.00,-1.00000,-1.000000,-1.000000,847.000000,0.000000
co2TailpipeGpm,37843.0,473.179736,122.188847,0.00,388.00000,467.736842,555.437500,1269.571429,167.437500
comb08,37843.0,20.195809,6.623444,7.00,17.00000,19.000000,23.000000,124.000000,6.000000
comb08U,37843.0,4.549751,10.389994,0.00,0.00000,0.000000,0.000000,124.360100,0.000000
cylinders,37844.0,0.996856,0.058752,0.00,1.00000,1.000000,1.000000,4.000000,0.000000
displ,37843.0,0.996829,0.056223,0.00,1.00000,1.000000,1.000000,1.000000,0.000000
engId,37843.0,8860.308961,17829.683477,0.00,0.00000,211.000000,4505.000000,69102.000000,4505.000000
feScore,37843.0,-0.035145,2.379584,-1.00,-1.00000,-1.000000,-1.000000,10.000000,0.000000
fuelCost08,37843.0,1882.060090,510.280408,550.00,1500.00000,1850.000000,2200.000000,5800.000000,700.000000
ghgScore,37843.0,-0.037206,2.374338,-1.00,-1.00000,-1.000000,-1.000000,10.000000,0.000000
highway08,37843.0,24.104881,6.963192,9.00,20.00000,24.000000,27.000000,111.000000,7.000000
highway08U,37843.0,5.438467,11.936327,0.00,0.00000,0.000000,0.000000,111.370000,0.000000
hlv,37843.0,2.026214,5.947989,0.00,0.00000,0.000000,0.000000,49.000000,0.000000
hpv,37843.0,10.424332,28.148770,0.00,0.00000,0.000000,0.000000,195.000000,0.000000
id,37843.0,19019.286235,11034.784855,1.00,9461.50000,18923.000000,28570.500000,38173.000000,19109.000000
lv2,37843.0,1.849219,4.429983,0.00,0.00000,0.000000,0.000000,41.000000,0.000000
lv4,37843.0,6.165658,9.743297,0.00,0.00000,0.000000,13.000000,55.000000,13.000000
pv2,37843.0,13.696113,31.269930,0.00,0.00000,0.000000,0.000000,194.000000,0.000000
pv4,37843.0,33.769125,45.914462,0.00,0.00000,0.000000,91.000000,192.000000,91.000000
UCity,37843.0,22.587229,9.350163,0.00,18.00000,21.000000,25.139300,197.577100,7.139300
UHighway,37843.0,33.619221,10.048326,0.00,27.10000,33.000000,38.109600,159.100000,11.009600
year,37843.0,2000.064398,10.390588,1984.00,1990.00000,2001.000000,2009.000000,2017.000000,19.000000
youSaveSpend,37843.0,-2658.999022,2553.098329,-22250.00,-4250.00000,-2500.000000,-750.000000,4000.000000,3500.000000

We will then create an empty data frame called outliers with the same columns as our data set. Finally, we will loop through each column in the data calculating the lower and upper bounds, retrieving records where the value for that column falls outside the bounds we established, and appending those results to our outlier data frame.

In [44]:
#Run this code

outliers = pd.DataFrame(columns=data.columns)

for col in stats.index:
    iqr = stats.at[col, 'IQR']
    cutoff = iqr * 1.5
    lower = stats.at[col, '25%'] - cutoff
    upper = stats.at[col, '75%'] + cutoff
    results = data[(data[col] < lower) | (data[col] > upper)].copy()
    results['Outlier'] = col
    outliers = pd.concat([outliers, results])

outliers.head()

,barrels08,city08,city08U,co2,co2TailpipeGpm,comb08,comb08U,cylinders,displ,drive,engId,feScore,fuelCost08,fuelType,fuelType1,ghgScore,highway08,highway08U,hlv,hpv,id,lv2,lv4,make,model,mpgData,phevBlended,pv2,pv4,trany,UCity,UHighway,VClass,year,youSaveSpend,createdOn,modifiedOn,Outlier
47,32.961,9.0,0.0,-1.0,888.7,10.0,0.0,1.0,1.0,Rear-Wheel Drive,2890.0,-1.0,3350.0,Regular,Regular Gasoline,-1.0,11.0,0.0,0.0,0.0,1004.0,0.0,0.0,Dodge,B150/B250 Wagon 2WD,N,False,0.0,0.0,Automatic 3-spd,11.0,15.0,Vans,1985.0,-10000.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,barrels08
58,32.961,10.0,0.0,-1.0,888.7,10.0,0.0,1.0,1.0,Rear-Wheel Drive,2854.0,-1.0,3350.0,Regular,Regular Gasoline,-1.0,11.0,0.0,0.0,0.0,1005.0,0.0,0.0,Dodge,B350 Wagon 2WD,N,False,0.0,0.0,Automatic 3-spd,12.0,15.0,Vans,1985.0,-10000.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,barrels08
69,32.961,10.0,0.0,-1.0,888.7,10.0,0.0,1.0,1.0,Rear-Wheel Drive,2850.0,-1.0,3350.0,Regular,Regular Gasoline,-1.0,11.0,0.0,0.0,0.0,1006.0,0.0,0.0,Dodge,B350 Wagon 2WD,N,False,0.0,0.0,Automatic 3-spd,12.0,15.0,Vans,1985.0,-10000.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,barrels08
80,32.961,9.0,0.0,-1.0,888.7,10.0,0.0,1.0,1.0,Rear-Wheel Drive,2890.0,-1.0,3350.0,Regular,Regular Gasoline,-1.0,10.0,0.0,0.0,0.0,1007.0,0.0,0.0,Dodge,B350 Wagon 2WD,N,False,0.0,0.0,Automatic 3-spd,11.0,14.0,Vans,1985.0,-10000.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,barrels08
275,32.961,9.0,0.0,-1.0,888.7,10.0,0.0,1.0,1.0,Rear-Wheel Drive,4880.0,-1.0,3350.0,Regular,Regular Gasoline,-1.0,12.0,0.0,0.0,0.0,10245.0,0.0,0.0,Chevrolet,C1500 Pickup 2WD,N,False,0.0,0.0,Automatic 4-spd,11.0,16.0,Standard Pickup Trucks,1993.0,-10000.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,barrels08

Our outliers data frame should now be populated with records that you can investigate further and determine whether they should be kept in the data or dropped. The Outlier column we added before appending the results for the column to the outliers data frame will let you know what column in each record contained the outlier. If you find that this method is returning too many results, you can be more stringent with your cutoff criteria (e.g. increasing the constant by which you multiply the IQR to 3 instead of 1.5).

# Data Type Correction

One common problem that is often overlooked is incorrect data types. This typically occurs when there is a numeric variable that should actually be represented as a categorical variable.

## Check the data type of each column

In [45]:
data_types = data.dtypes
print(data_types)

barrels08         float64
city08            float64
city08U           float64
co2               float64
co2TailpipeGpm    float64
comb08            float64
comb08U           float64
cylinders         float64
displ             float64
drive              object
engId             float64
feScore           float64
fuelCost08        float64
fuelType           object
fuelType1          object
ghgScore          float64
highway08         float64
highway08U        float64
hlv               float64
hpv               float64
id                float64
lv2               float64
lv4               float64
make               object
model              object
mpgData            object
phevBlended        object
pv2               float64
pv4               float64
trany              object
UCity             float64
UHighway          float64
VClass             object
year              float64
youSaveSpend      float64
createdOn          object
modifiedOn         object
dtype: object

## Cleaning years
Do you think column year is a continuous variable? Would you change it onto another dtype?

In [46]:
data = data.dropna(subset=['year'])

In [47]:
data['year'] = data['year'].astype(int)

You can apply this technique to any column whose data type you would like to change.

In [48]:
data['cylinders'] = data['cylinders'].dropna().astype(int)

In [49]:
data_types = data.dtypes
print(data_types)

barrels08         float64
city08            float64
city08U           float64
co2               float64
co2TailpipeGpm    float64
comb08            float64
comb08U           float64
cylinders           int32
displ             float64
drive              object
engId             float64
feScore           float64
fuelCost08        float64
fuelType           object
fuelType1          object
ghgScore          float64
highway08         float64
highway08U        float64
hlv               float64
hpv               float64
id                float64
lv2               float64
lv4               float64
make               object
model              object
mpgData            object
phevBlended        object
pv2               float64
pv4               float64
trany              object
UCity             float64
UHighway          float64
VClass             object
year                int32
youSaveSpend      float64
createdOn          object
modifiedOn         object
dtype: object

# Cleaning Text and Removing Special Characters

The presence of special characters in our fields has the potential to make analyzing our data challenging. Imagine not being able to perform calculations on a numeric field because it was currently represented as an object data type due to the fact that it had a dollar sign ($) in it. 

Similarly, imagine having a categorical field where you could not group records that belong in the same group together because in one field you are grouping by, terms that refer to the same thing are sometimes hyphenated. In cases like this, it is necessary to remove special characters so that we can properly analyze the data.

In our vehicles data set, the trany field has several special characters (parentheses, hyphens, etc.). Check the unique values and clean the column.

hint: check the `replace` function

In [50]:
#Primero, verifico los valores únicos en la columna trany para comprender qué caracteres especiales necesito eliminar. 
unique_trany_values = data['trany'].unique()
print(unique_trany_values)

['Manual 5-spd' 'Automatic 3-spd' 'Automatic 4-spd' 'Automatic 5-spd'
 'Manual 4-spd' 'Manual 3-spd' 'Manual 6-spd' 'Automatic (S5)'
 'Automatic (variable gear ratios)' 'Automatic 6-spd' 'Automatic (S6)'
 'Automatic (S4)' 'Automatic 7-spd' 'Automatic (S7)' 'Automatic (S8)'
 'Automatic (AM5)' 'Auto(AM6)' 'Auto(AV-S7)' 'Automatic (A6)'
 'Automatic (AV-S6)' 'Auto(AM7)' 'Manual 4-spd Doubled' 'Manual 5 spd'
 'Automatic (AM6)' 'Manual 7-spd' 'Auto(L4)' 'Auto(L3)' 'Automatic (AV)'
 'Auto (AV-S6)' 'Auto(AM5)' 'Auto(AV-S6)' 'Auto (AV-S8)' 'Automatic 8-spd'
 'Auto(AV-S8)' 'Automatic (A1)' 'Auto (AV)' 'Auto(AM-S6)' 'Auto(AM-S7)'
 'Automatic 6spd' 'Automatic 9-spd' 'Automatic (S9)' 'Auto(AM-S8)'
 'Auto(A1)' 'Auto(AM8)' 'Manual(M7)' 'Auto(AM-S9)']

In [51]:
data['trany'] = data['trany'].str.replace('(', '').str.replace(')', '').str.replace('-', '')

In [52]:
unique_trany_values_cleaned = data['trany'].unique()
print(unique_trany_values_cleaned)

['Manual 5spd' 'Automatic 3spd' 'Automatic 4spd' 'Automatic 5spd'
 'Manual 4spd' 'Manual 3spd' 'Manual 6spd' 'Automatic S5'
 'Automatic variable gear ratios' 'Automatic 6spd' 'Automatic S6'
 'Automatic S4' 'Automatic 7spd' 'Automatic S7' 'Automatic S8'
 'Automatic AM5' 'AutoAM6' 'AutoAVS7' 'Automatic A6' 'Automatic AVS6'
 'AutoAM7' 'Manual 4spd Doubled' 'Manual 5 spd' 'Automatic AM6'
 'Manual 7spd' 'AutoL4' 'AutoL3' 'Automatic AV' 'Auto AVS6' 'AutoAM5'
 'AutoAVS6' 'Auto AVS8' 'Automatic 8spd' 'AutoAVS8' 'Automatic A1'
 'Auto AV' 'AutoAMS6' 'AutoAMS7' 'Automatic 9spd' 'Automatic S9'
 'AutoAMS8' 'AutoA1' 'AutoAM8' 'ManualM7' 'AutoAMS9']

As you can see, we now have no special characters, consistent naming, and proper spacing. We started out with 47 unique values in this column, and using this technique, we were able to reduce the number of unique values to 39.



# Finding and Removing Duplicates

The final topic we are going to cover in this lab is how to identify and remove duplicate rows (or rows that refer to the same entity) in our data. When trying to identify duplicates, we will use the columns (or attributes) of the data to help us determine what entities are similar enough to be considered the same entity. We want to start with all the columns we currently have available to us and work our way toward a lesser number of attributes in an intuitive fashion. In this process, the act of dropping duplicated records is easy, but identifying the correct attributes for comparison and which records to drop is sometimes quite challenging.

The first thing we will do is attempt to drop any duplicate records, considering all the columns we currently have in the data set. 

Pandas provides us with the ability to do that via the `drop_duplicates method`.

## Drop duplicate rows that are completely equal

In [53]:
data.drop_duplicates(inplace=True)

This tells us that there were no records that matched exactly across all columns. However, if we reduce the number of columns in our data that we are interested in, we can try again and have a higher likelihood of finding duplicate records.

## Select a subset of columns, remove all other columns, and then use the drop_duplicates method to drop any duplicate records based on the remaining columns.

In [55]:

subset_columns = ['barrels08', 'city08', 'co2TailpipeGpm', 'comb08', 'cylinders', 'displ', 'drive']

data_subset = data[subset_columns]

before = len(data_subset)

data_subset.drop_duplicates(inplace=True)

after = len(data_subset)

#print('Number of duplicate records dropped: ', str(before - after))
print('Number of duplicate records dropped:', before - after)

Number of duplicate records dropped: 35299

With the reduced number of columns, we were able to identify and drop 885 duplicate records.

# Export clean dataset
Export your bright new clean dataset into a csv file and store it in data folder.

In [ ]:
# Especifica la ruta del archivo CSV limpio
output_csv_file = 'data/clean_dataset.csv'

# Exporta el DataFrame limpio a un archivo CSV
data_subset.to_csv(output_csv_file, index=False)

print(f"El conjunto de datos limpio se ha exportado a '{output_csv_file}'.")